### ISSUE TITLE
Fargate task number reduced to 0

### ISSUE THREAD

**Issue by viyullas** [diodonfrost/terraform-aws-lambda-scheduler-stop-start#14]
##### SUMMARY
It would be nice to implement the same logic to reduce the number of Fargate ECS tasks to 0 in a tagged service
##### ISSUE TYPE
Just the same way we can reduce the number of EC2 instances in the ASG assigned to an ECS cluster it would be of great use to get something similar to reduce the costs of fargate tasks. 

##### Additional context
Great module. It is very usefull.

**Comment by diodonfrost** [comment]
Great idea.
I'm going to check if it is possible.

**Comment by vladimirjaric** [comment]
We run most of our workload in ECS Fargate, so this would be great if possible. We already use this module for EC2 and RDS scheduling.

@diodonfrost, any idea when this could be out? Thank you

**Comment by diodonfrost** [comment]
Upon further inspection and considering the state of the fargate service, that won't be possible.
Stopping Fargate-task is not realy a problem but starting/running Fargate-task need some specific settings like subnet, vpc, ecs-cluster, etc that are specific to each Fargate-apps and cannot be determined by this Terraform module.

**Comment by viyullas** [comment]
I have solved it using aws_appautoscaling_target and aws_appautoscaling_scheduled_action just in case somebody needs a similar solution.

**Comment by waneal** [comment]
@diodonfrost 

Thank you for this great module! 

> Stopping Fargate-task is not realy a problem but starting/running Fargate-task need some specific settings like subnet, vpc, ecs-cluster, etc that are specific to each Fargate-apps and cannot be determined by this Terraform module.

I think, if we focus on only ECS Service, we don't have to consider subnets and vpc. `resourcegroupstaggingapi` can get ECS service arn including cluster name, so we can start/stop ecs service through `UpdateService` action. How about this method?

```
> aws resourcegroupstaggingapi get-resources --resource-type-filters ecs:service
{
    "ResourceTagMappingList": [
        {
            "ResourceARN": "arn:aws:ecs:REGION:ACCOUNT_ID:service/CLUSTER_NAME/SERVICE_NAME",
            "Tags": [
                {
                    "Key": "Key",
                    "Value": "Value"
                }
            ]
        }
    ]
}
```

**Comment by n3mawashi** [comment]
See PR https://github.com/diodonfrost/terraform-aws-lambda-scheduler-stop-start/pull/27 to resolve this
