### ISSUE TITLE
Feature request: timezone support to specify cron

### ISSUE THREAD

**Issue by rngadam** [diodonfrost/terraform-aws-lambda-scheduler-stop-start#2]
Saw this in another terraform module:

https://github.com/neillturner/terraform-aws-lambda-scheduler

```
  time = "Europe/London"
```

would be helpful

**Comment by diodonfrost** [comment]
Hello

Right now I wouldn't integrate this feature in the python code part. I would prefer to integrate it in Cloudwatch event but the cron support in AWS Cloudwatch is really limited and its doesn't support timezone.
