### ISSUE TITLE
Support scheduling an elasticsearch (opensearch) cluster

### ISSUE THREAD

**Issue by schollii** [diodonfrost/terraform-aws-lambda-scheduler-stop-start#39]
##### SUMMARY

Support scheduling an elasticsearch (opensearch) cluster

##### ISSUE TYPE
- Feature Idea

**Comment by diodonfrost** [comment]
Hello,
At the moment, We cannot stop or start an AWS OpenSearch cluster or maybe I missed something?

https://boto3.amazonaws.com/v1/documentation/api/1.18.51/reference/services/opensearch.html
