### ISSUE TITLE
Disable CloudWatch alarm actions

### ISSUE THREAD

**Issue by kamac** [diodonfrost/terraform-aws-lambda-scheduler-stop-start#4]
##### SUMMARY
Allow to enable/disable cloudwatch alarm actions like it's possible for ec2 instances.

##### ISSUE TYPE
I'd like to use this module to create scheduled downtime. However, I have several alarms set up, so whenever I stop my instances, I get alerts that something's broken when really it's not. It would be good to be able to disable cloudwatch alarm actions along with instances.

##### Additional context
Should be possible via:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_EnableAlarmActions.html
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DisableAlarmActions.html

**Comment by diodonfrost** [comment]
Thanks for the report.
I will make a PR  for this.

**Comment by diodonfrost** [comment]
Fixed in version [2.6.0](https://github.com/diodonfrost/terraform-aws-lambda-scheduler-stop-start/releases/tag/2.6.0)

Feel free to give me your feedback.

**Comment by kamac** [comment]
Thanks a lot! In the end, I'll need to modify my AutoScaling groups to scale the system down & up, since I have an EKS cluster and iptables get messed up if I stop & start individual EC2 instances. I'll probably just fork your module and modify it to match my needs. Thanks again 🙌

**Comment by kamac** [comment]
However, it would be good to be able to schedule cloudwatch alarms without enabling/disabling EC2/autoscaling groups. That way I could use `aws_autoscaling_schedule` for autoscaling groups, and this module for RDS & cloudwatch 🙏

**Comment by kamac** [comment]
Just wanted to let you know that I ended up writing my own module, using yours as a template. Big thanks anyway 👍
